// Copyright 2014 Google Inc. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/* global goog */

goog.addDependency('../../apphosting/api/urlfetch_service.pb.js', ['apphosting.URLFetchServiceError', 'apphosting.URLFetchServiceError.ErrorCode', 'apphosting.URLFetchRequest', 'apphosting.URLFetchRequest.Header', 'apphosting.URLFetchRequest.RequestMethod', 'apphosting.URLFetchResponse', 'apphosting.URLFetchResponse.Header'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/dos/dos_service.pb.js', ['apphosting.DosServiceError', 'apphosting.DosServiceError.ErrorCode', 'apphosting.BlacklistEntry', 'apphosting.DosConfiguration', 'apphosting.SetDosConfigRequest', 'apphosting.SetDosConfigResponse', 'apphosting.GetDosConfigRequest', 'apphosting.GetDosConfigResponse', 'apphosting.ListRequest', 'apphosting.ListRequest.Category', 'apphosting.TopUsersRequest', 'apphosting.TopUser', 'apphosting.UsersList', 'apphosting.TopUsersResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/ext/remote_api/remote_api.pb.js', ['apphosting.ext.remote_api.Request', 'apphosting.ext.remote_api.ApplicationError', 'apphosting.ext.remote_api.RpcError', 'apphosting.ext.remote_api.RpcError.ErrorCode', 'apphosting.ext.remote_api.Response'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/memcache/memcache_service.pb.js', ['apphosting.MemcacheServiceError', 'apphosting.MemcacheServiceError.ErrorCode', 'apphosting.AppOverride', 'apphosting.MemcacheGetRequest', 'apphosting.MemcacheGetResponse', 'apphosting.MemcacheGetResponse.Item', 'apphosting.MemcacheSetRequest', 'apphosting.MemcacheSetRequest.Item', 'apphosting.MemcacheSetRequest.SetPolicy', 'apphosting.MemcacheSetResponse', 'apphosting.MemcacheSetResponse.SetStatusCode', 'apphosting.MemcacheDeleteRequest', 'apphosting.MemcacheDeleteRequest.Item', 'apphosting.MemcacheDeleteResponse', 'apphosting.MemcacheDeleteResponse.DeleteStatusCode', 'apphosting.MemcacheIncrementRequest', 'apphosting.MemcacheIncrementRequest.Direction', 'apphosting.MemcacheIncrementResponse', 'apphosting.MemcacheIncrementResponse.IncrementStatusCode', 'apphosting.MemcacheBatchIncrementRequest', 'apphosting.MemcacheBatchIncrementResponse', 'apphosting.MemcacheFlushRequest', 'apphosting.MemcacheFlushResponse', 'apphosting.MemcacheStatsRequest', 'apphosting.MergedNamespaceStats', 'apphosting.MemcacheStatsResponse', 'apphosting.MemcacheGrabTailRequest', 'apphosting.MemcacheGrabTailResponse', 'apphosting.MemcacheGrabTailResponse.Item'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/channel/channel_service.pb.js', ['apphosting.ChannelServiceError', 'apphosting.ChannelServiceError.ErrorCode', 'apphosting.CreateChannelRequest', 'apphosting.CreateChannelResponse', 'apphosting.SendMessageRequest'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/blobstore/blobstore_upload.pb.js', ['apphosting.BlobstoreUploadInfo', 'apphosting.BlobInfo', 'apphosting.BlobRecord', 'apphosting.BlobUploadCheckpoint'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/logservice/log_service.pb.js', ['apphosting.LogServiceError', 'apphosting.LogServiceError.ErrorCode', 'apphosting.UserAppLogLine', 'apphosting.UserAppLogGroup', 'apphosting.FlushRequest', 'apphosting.SetStatusRequest', 'apphosting.LogOffset', 'apphosting.LogLine', 'apphosting.RequestLog', 'apphosting.LogModuleVersion', 'apphosting.LogReadRequest', 'apphosting.LogReadResponse', 'apphosting.LogUsageRecord', 'apphosting.LogUsageRequest', 'apphosting.LogUsageResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/modules/modules_service.pb.js', ['apphosting.ModulesServiceError', 'apphosting.ModulesServiceError.ErrorCode', 'apphosting.GetModulesRequest', 'apphosting.GetModulesResponse', 'apphosting.GetVersionsRequest', 'apphosting.GetVersionsResponse', 'apphosting.GetDefaultVersionRequest', 'apphosting.GetDefaultVersionResponse', 'apphosting.GetNumInstancesRequest', 'apphosting.GetNumInstancesResponse', 'apphosting.SetNumInstancesRequest', 'apphosting.SetNumInstancesResponse', 'apphosting.StartModuleRequest', 'apphosting.StartModuleResponse', 'apphosting.StopModuleRequest', 'apphosting.StopModuleResponse', 'apphosting.GetHostnameRequest', 'apphosting.GetHostnameResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/app_identity/app_identity_service.pb.js', ['apphosting.AppIdentityServiceError', 'apphosting.AppIdentityServiceError.ErrorCode', 'apphosting.SignForAppRequest', 'apphosting.SignForAppResponse', 'apphosting.GetPublicCertificateForAppRequest', 'apphosting.PublicCertificate', 'apphosting.GetPublicCertificateForAppResponse', 'apphosting.GetServiceAccountNameRequest', 'apphosting.GetServiceAccountNameResponse', 'apphosting.GetAccessTokenRequest', 'apphosting.GetAccessTokenResponse', 'apphosting.GetDefaultGcsBucketNameRequest', 'apphosting.GetDefaultGcsBucketNameResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/files/file_service.pb.js', ['apphosting.files.FileServiceErrors', 'apphosting.files.FileServiceErrors.ErrorCode', 'apphosting.files.KeyValue', 'apphosting.files.KeyValues', 'apphosting.files.FileContentType', 'apphosting.files.FileContentType.ContentType', 'apphosting.files.CreateRequest', 'apphosting.files.CreateRequest.Parameter', 'apphosting.files.CreateResponse', 'apphosting.files.OpenRequest', 'apphosting.files.OpenRequest.OpenMode', 'apphosting.files.OpenResponse', 'apphosting.files.CloseRequest', 'apphosting.files.CloseResponse', 'apphosting.files.FileStat', 'apphosting.files.StatRequest', 'apphosting.files.StatResponse', 'apphosting.files.AppendRequest', 'apphosting.files.AppendResponse', 'apphosting.files.DeleteRequest', 'apphosting.files.DeleteResponse', 'apphosting.files.ReadRequest', 'apphosting.files.ReadResponse', 'apphosting.files.ReadKeyValueRequest', 'apphosting.files.ReadKeyValueResponse', 'apphosting.files.ReadKeyValueResponse.KeyValue', 'apphosting.files.ShuffleEnums', 'apphosting.files.ShuffleEnums.InputFormat', 'apphosting.files.ShuffleEnums.OutputFormat', 'apphosting.files.ShuffleEnums.Status', 'apphosting.files.ShuffleInputSpecification', 'apphosting.files.ShuffleOutputSpecification', 'apphosting.files.ShuffleRequest', 'apphosting.files.ShuffleRequest.Callback', 'apphosting.files.ShuffleResponse', 'apphosting.files.GetShuffleStatusRequest', 'apphosting.files.GetShuffleStatusResponse', 'apphosting.files.GetCapabilitiesRequest', 'apphosting.files.GetCapabilitiesResponse', 'apphosting.files.FinalizeRequest', 'apphosting.files.FinalizeResponse', 'apphosting.files.GetDefaultGsBucketNameRequest', 'apphosting.files.GetDefaultGsBucketNameResponse', 'apphosting.files.ListDirRequest', 'apphosting.files.ListDirResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/user_service.pb.js', ['apphosting.UserServiceError', 'apphosting.UserServiceError.ErrorCode', 'apphosting.CreateLoginURLRequest', 'apphosting.CreateLoginURLResponse', 'apphosting.CreateLogoutURLRequest', 'apphosting.CreateLogoutURLResponse', 'apphosting.GetOAuthUserRequest', 'apphosting.GetOAuthUserResponse', 'apphosting.CheckOAuthSignatureRequest', 'apphosting.CheckOAuthSignatureResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/taskqueue/taskqueue_service.pb.js', ['apphosting.TaskQueueServiceError', 'apphosting.TaskQueueServiceError.ErrorCode', 'apphosting.TaskPayload', 'apphosting.TaskQueueRetryParameters', 'apphosting.TaskQueueAcl', 'apphosting.TaskQueueHttpHeader', 'apphosting.TaskQueueMode', 'apphosting.TaskQueueMode.Mode', 'apphosting.TaskQueueAddRequest', 'apphosting.TaskQueueAddRequest.Header', 'apphosting.TaskQueueAddRequest.CronTimetable', 'apphosting.TaskQueueAddRequest.RequestMethod', 'apphosting.TaskQueueAddResponse', 'apphosting.TaskQueueBulkAddRequest', 'apphosting.TaskQueueBulkAddResponse', 'apphosting.TaskQueueBulkAddResponse.TaskResult', 'apphosting.TaskQueueDeleteRequest', 'apphosting.TaskQueueDeleteResponse', 'apphosting.TaskQueueForceRunRequest', 'apphosting.TaskQueueForceRunResponse', 'apphosting.TaskQueueUpdateQueueRequest', 'apphosting.TaskQueueUpdateQueueResponse', 'apphosting.TaskQueueFetchQueuesRequest', 'apphosting.TaskQueueFetchQueuesResponse', 'apphosting.TaskQueueFetchQueuesResponse.Queue', 'apphosting.TaskQueueFetchQueueStatsRequest', 'apphosting.TaskQueueScannerQueueInfo', 'apphosting.TaskQueueFetchQueueStatsResponse', 'apphosting.TaskQueueFetchQueueStatsResponse.QueueStats', 'apphosting.TaskQueuePauseQueueRequest', 'apphosting.TaskQueuePauseQueueResponse', 'apphosting.TaskQueuePurgeQueueRequest', 'apphosting.TaskQueuePurgeQueueResponse', 'apphosting.TaskQueueDeleteQueueRequest', 'apphosting.TaskQueueDeleteQueueResponse', 'apphosting.TaskQueueDeleteGroupRequest', 'apphosting.TaskQueueDeleteGroupResponse', 'apphosting.TaskQueueQueryTasksRequest', 'apphosting.TaskQueueQueryTasksResponse', 'apphosting.TaskQueueQueryTasksResponse.Task', 'apphosting.TaskQueueQueryTasksResponse.Task.Header', 'apphosting.TaskQueueQueryTasksResponse.Task.CronTimetable', 'apphosting.TaskQueueQueryTasksResponse.Task.RunLog', 'apphosting.TaskQueueQueryTasksResponse.Task.RequestMethod', 'apphosting.TaskQueueFetchTaskRequest', 'apphosting.TaskQueueFetchTaskResponse', 'apphosting.TaskQueueUpdateStorageLimitRequest', 'apphosting.TaskQueueUpdateStorageLimitResponse', 'apphosting.TaskQueueQueryAndOwnTasksRequest', 'apphosting.TaskQueueQueryAndOwnTasksResponse', 'apphosting.TaskQueueQueryAndOwnTasksResponse.Task', 'apphosting.TaskQueueModifyTaskLeaseRequest', 'apphosting.TaskQueueModifyTaskLeaseResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/mail_service.pb.js', ['apphosting.MailServiceError', 'apphosting.MailServiceError.ErrorCode', 'apphosting.MailAttachment', 'apphosting.MailHeader', 'apphosting.MailMessage'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/capabilities/capability_service.pb.js', ['apphosting.IsEnabledRequest', 'apphosting.IsEnabledResponse', 'apphosting.IsEnabledResponse.SummaryStatus'], ['apphosting.CapabilityConfig', 'goog.proto2.Message']);
goog.addDependency('../../apphosting/api/system/system_service.pb.js', ['apphosting.SystemServiceError', 'apphosting.SystemServiceError.ErrorCode', 'apphosting.SystemStat', 'apphosting.GetSystemStatsRequest', 'apphosting.GetSystemStatsResponse', 'apphosting.StartBackgroundRequestRequest', 'apphosting.StartBackgroundRequestResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/api_base.pb.js', ['apphosting.base.StringProto', 'apphosting.base.Integer32Proto', 'apphosting.base.Integer64Proto', 'apphosting.base.BoolProto', 'apphosting.base.DoubleProto', 'apphosting.base.BytesProto', 'apphosting.base.VoidProto'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/base/capabilities.pb.js', ['apphosting.CapabilityConfigList', 'apphosting.CapabilityConfig', 'apphosting.CapabilityConfig.Status'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/images/images_service.pb.js', ['apphosting.ImagesServiceError', 'apphosting.ImagesServiceError.ErrorCode', 'apphosting.ImagesServiceTransform', 'apphosting.ImagesServiceTransform.Type', 'apphosting.Transform', 'apphosting.ImageData', 'apphosting.InputSettings', 'apphosting.InputSettings.ORIENTATION_CORRECTION_TYPE', 'apphosting.OutputSettings', 'apphosting.OutputSettings.MIME_TYPE', 'apphosting.ImagesTransformRequest', 'apphosting.ImagesTransformResponse', 'apphosting.CompositeImageOptions', 'apphosting.CompositeImageOptions.ANCHOR', 'apphosting.ImagesCanvas', 'apphosting.ImagesCompositeRequest', 'apphosting.ImagesCompositeResponse', 'apphosting.ImagesHistogramRequest', 'apphosting.ImagesHistogram', 'apphosting.ImagesHistogramResponse', 'apphosting.ImagesGetUrlBaseRequest', 'apphosting.ImagesGetUrlBaseResponse', 'apphosting.ImagesDeleteUrlBaseRequest', 'apphosting.ImagesDeleteUrlBaseResponse'], ['goog.proto2.Message']);
goog.addDependency('../../apphosting/api/blobstore/blobstore_service.pb.js', ['apphosting.BlobstoreServiceError', 'apphosting.BlobstoreServiceError.ErrorCode', 'apphosting.CreateUploadURLRequest', 'apphosting.CreateUploadURLResponse', 'apphosting.DeleteBlobRequest', 'apphosting.FetchDataRequest', 'apphosting.FetchDataResponse', 'apphosting.CloneBlobRequest', 'apphosting.CloneBlobResponse', 'apphosting.DecodeBlobKeyRequest', 'apphosting.DecodeBlobKeyResponse', 'apphosting.CreateEncodedGoogleStorageKeyRequest', 'apphosting.CreateEncodedGoogleStorageKeyResponse'], ['goog.proto2.Message']);
goog.addDependency('../../net/proto2/contrib/WireSerializer.js', ['net.proto2.contrib.WireSerializer'], ['goog.asserts', 'goog.math.Long', 'goog.proto2.Message', 'goog.proto2.Serializer']);
